version: "3.9"

services:
  mongo-pagos:
    image: mongo:6         
    container_name: mongo-pagos
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_pagos_data:/data/db

  pagos-service:
    build: .              
    container_name: smart-ride-servicio-pagos
    restart: always
    depends_on:
      - mongo-pagos
    environment:
      MONGO_URI: "mongodb://mongo-pagos:27017"
      MONGO_DB: "smart_ride_pagos"
      RUST_LOG: "info"
    ports:
      - "4000:4000"

volumes:
  mongo_pagos_data:
