events {}
http {
  upstream pagos { server servicio_pagos:8080; }

  server {
    listen 80;
    # CRUD pagos vía proxy
    location /api/pagos/ { proxy_pass http://pagos/; }
    location /api/pagos/docs/ { proxy_pass http://pagos/; }
  }
}
